### PR TITLE
fix: prevent click on flag to trigger bomb

### LINKED ISSUE #107: Left-Click on Flag triggers the bomb
When a flag is set on a tile and it afterwards left-clicked, the bomb explodes. The "original" windows-minesweeper had a securing mechanism to avoid left-clicks on flags. Flags had to be removed before the bomb can be triggered.

If this is by design, it is ok for me, but it just ruined a hard game for me just before winning.

### PR DESCRIPTION
**Pull request by wtho**
Added a check in `onCellClick` if the field is flagged before triggering the game over / reveal.

Closes #107

### CODE REVIEW

File: src/mine-sweeper.tsx [hunk 1]
```diff
@@ -244,6 +244,9 @@ export default class MineSweeper extends React.Component<IMineSweeperProps, IMin
       });
       this.timerId = window.setInterval(this.updateTimer.bind(this), 1000);
     }
+    if (this.isFlagged(x, y)) {
```
Comment (Knochenmark) [inline src/mine-sweeper.tsx]: Great to see that you've added `isFlagged` as helper method. The condition could be part of the early return in line `238` though. I suggest you just add another OR and the isFlagged check as third condition.

**Comment by Knochenmark** [comment]
Great 👍 thanks for your contribution
